### ISSUE TITLE
Update on rewrite rule 

### ISSUE THREAD

**Issue by cbrassel** [Gregy/apache_mod_realpatch#1]
Hello,
Thank you for this, you saved my live ! or sort of .. 
In any case it's a great piece of code that help's me solving a big issue I had with apache and php-fpm.
I want just give a little update on how I have implemented this in the rewrite rules, to give a little context ;
2 apache servers, 6 php-fpm servers, 1 nfs for the sharing of the code between all the servers and HAProxy for the load-balancing between apache and php-fpm servers. 
The rewrite rules I have applied :
```
RewriteEngine On
RewriteMap realpath int:realpath
RewriteCond %{DOCUMENT_ROOT}%{REQUEST_FILENAME} "\.php$"
RewriteRule "(.*)" "${realpath:%{DOCUMENT_ROOT}%{REQUEST_FILENAME}}" [L]
``` 
Maybe it can helps somebody else ..

Regards
Claude

**Comment by Gregy** [comment]
Hi, thank you for the kind words and an example usage :-)
